# VERSIÓN PYTHON A UTILIZAR (EN CONSOLA python --version)
FROM python:3.9  
# SOLO EXISTE ESTA VARAIBLE (CONTRASEÑA) EN MI EQUIPO O SERVIDOR (SEGURIDAD)
ENV PYTHONUNBUFFERED 1
# CREAR UNA CARPETA
RUN mkdir /users
# INDICAR NUESTRO DIRECTORIO SOBRE EL QUE SE VA A TRABAJAR
WORKDIR /users
# AGREGA TODO A UNA CARPETA
ADD . /users/
# IMPORTAR LIBRERIAS
RUN pip install -r requirements.txt
# EN DONDE VA A ESTAR EXPUESTO A NIVEL DE INTERNET
EXPOSE 8080
# EJECUTAR COMANDOS
CMD python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:$PORT